import { Activity, ArrowUpRight, Database, RefreshCw, Server, ShieldCheck } from 'lucide-react';
import type { HealthInfo } from '../api';

interface Props { health: HealthInfo | null; connection: string; onRefresh: () => Promise<void> }
export function ConcurrencyTab({ health, connection, onRefresh }: Props) {
  const ready = connection === 'connected';
  return <div className="secondary-page"><div className="page-heading"><div className="eyebrow">BEHIND YOUR WORKSPACE</div><h1>A clear view of your system.</h1><p>Real connection status. Reported configuration. No invented live metrics.</p></div><section className="panel"><div className="panel-toolbar"><div><h2>Backend connection</h2><p>Checked against the server's readiness endpoint.</p></div><button className="button" disabled={connection === 'checking'} onClick={() => void onRefresh()}><RefreshCw size={15} className={connection === 'checking' ? 'spin' : ''} />Refresh status</button></div><div className={`connection-card ${ready ? 'ready' : ''}`}><span className="connection-icon"><Server size={26} /></span><div><h3>{ready ? 'Ready for research' : connection === 'checking' ? 'Checking the backend...' : health ? 'Backend is reachable, but setup is incomplete' : 'Your backend is not connected'}</h3><p>{ready ? `Backend version ${health?.version}. The readiness check returned OK.` : 'Start the FastAPI backend and configure its research services to run real queries.'}</p></div><span className={`status-pill ${ready ? 'success' : 'neutral'}`}>{health?.status || connection}</span></div>
    <div className="system-metrics"><div><Database size={19} /><span>Indexed passages</span><strong>{health?.vector_store_documents ?? '—'}</strong><small>Reported by the vector store</small></div><div><Activity size={19} /><span>Server uptime</span><strong>{health ? `${Math.floor(health.uptime_seconds / 60)} min` : '—'}</strong><small>At the last readiness check</small></div><div><ShieldCheck size={19} /><span>Latency target</span><strong>{health ? `${health.latency_sla_seconds}s` : '—'}</strong><small>Configured target, not measured latency</small></div></div><div className="inset"><div className="alert"><div><strong>What this page can tell you</strong><p>The backend exposes readiness, indexed passage count, uptime, and configured targets. Live concurrency, throughput, and latency percentiles are not currently exposed by an API.</p></div></div></div></section><section className="panel setup-panel"><h2>Connect your research backend</h2><p>Run the backend from the repository root in your configured Python environment:</p><pre><code>uvicorn app.main:app --host 127.0.0.1 --port 8000</code></pre><p>The frontend forwards API and health requests to port 8000 during development. Add the required environment settings before running real research.</p><a className="text-button" href="https://github.com/smit45-m/multi-agent-research-assistant#readme" target="_blank" rel="noreferrer">Project setup instructions <ArrowUpRight size={14} /></a>{health && <a className="text-button" href="/docs" target="_blank" rel="noreferrer">Open API reference <ArrowUpRight size={14} /></a>}</section></div>;
}
